version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=demo
      - MINIO_ROOT_PASSWORD=demo123!
volumes:
  minio_data:
    driver: local
